"""Format scoring breakdowns into HTML + plain-text alert emails."""

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from src.ingestion.schemas import NewsArticle
from src.scoring.models import ScoreBreakdown


def _factor_rows_html(breakdown: ScoreBreakdown) -> str:
    rows = ""
    for key, fs in sorted(breakdown.factors.items(), key=lambda kv: -abs(kv[1].contribution)):
        rows += (
            f"<tr>"
            f"<td style='padding:4px 8px;'>{key}</td>"
            f"<td style='padding:4px 8px;text-align:right;'>{fs.raw:,.2f}</td>"
            f"<td style='padding:4px 8px;text-align:right;'>{fs.z_score:+.2f}</td>"
            f"<td style='padding:4px 8px;text-align:right;'>{fs.weight:.2f}</td>"
            f"<td style='padding:4px 8px;text-align:right;'>{fs.contribution:+.4f}</td>"
            f"</tr>"
        )
    return rows


def _factor_rows_text(breakdown: ScoreBreakdown) -> str:
    lines = []
    for key, fs in sorted(breakdown.factors.items(), key=lambda kv: -abs(kv[1].contribution)):
        lines.append(f"  {key:<16s}  raw={fs.raw:>12,.2f}  z={fs.z_score:+.2f}  w={fs.weight:.2f}  c={fs.contribution:+.4f}")
    return "\n".join(lines)


def format_alert_email(
    breakdown: ScoreBreakdown,
    news: list[NewsArticle] | None = None,
    is_update: bool = False,
) -> MIMEMultipart:
    """Build an HTML+text MIME message for a triggered alert."""
    prefix = "UPDATE: " if is_update else ""
    subject = f"{prefix}Option Alert: {breakdown.ticker} — score {breakdown.composite_score:.1f}"

    direction = "CALL" if breakdown.contract_type.lower() == "call" else "PUT"

    # --- HTML body ---
    news_html = ""
    if news:
        news_items = "".join(
            f"<li>{a.title} <small>({a.published_utc.strftime('%Y-%m-%d %H:%M') if a.published_utc else 'N/A'})</small></li>"
            for a in news[:5]
        )
        news_html = f"<h3>Recent News</h3><ul>{news_items}</ul>"

    html = f"""
    <html><body style="font-family:Arial,sans-serif;max-width:700px;">
    <h2 style="color:#d32f2f;">{prefix}Anomaly Detected: {breakdown.ticker} {direction}</h2>
    <table style="border-collapse:collapse;">
      <tr><td><b>Contract</b></td><td>{breakdown.contract}</td></tr>
      <tr><td><b>Strike</b></td><td>${breakdown.strike_price:,.2f} {direction} exp {breakdown.expiration_date}</td></tr>
      <tr><td><b>Composite Score</b></td><td><b>{breakdown.composite_score:.2f}</b> / 10</td></tr>
      <tr><td><b>Option Price</b></td><td>${breakdown.option_price:,.2f}</td></tr>
      <tr><td><b>Volume</b></td><td>{breakdown.option_volume:,}</td></tr>
      <tr><td><b>Open Interest</b></td><td>{breakdown.open_interest:,}</td></tr>
      <tr><td><b>Underlying Price</b></td><td>${breakdown.underlying_price:,.2f}</td></tr>
      <tr><td><b>Underlying Move</b></td><td>{breakdown.underlying_move_pct:+.2f}%</td></tr>
      <tr><td><b>Already Priced In</b></td><td>{'Yes' if breakdown.already_priced_in else 'No'}</td></tr>
      <tr><td><b>Detected At</b></td><td>{breakdown.timestamp.strftime('%Y-%m-%d %H:%M:%S')} UTC</td></tr>
    </table>

    <h3>Factor Breakdown</h3>
    <table style="border-collapse:collapse;border:1px solid #ccc;">
      <tr style="background:#f0f0f0;">
        <th style="padding:4px 8px;">Factor</th>
        <th style="padding:4px 8px;">Raw</th>
        <th style="padding:4px 8px;">Z-Score</th>
        <th style="padding:4px 8px;">Weight</th>
        <th style="padding:4px 8px;">Contribution</th>
      </tr>
      {_factor_rows_html(breakdown)}
    </table>

    {news_html}

    <p style="color:#888;font-size:12px;">
      Generated by Option Finder at {breakdown.timestamp.strftime('%Y-%m-%d %H:%M:%S')} UTC.
      This is not financial advice.
    </p>
    </body></html>
    """

    # --- Plain text body ---
    news_text = ""
    if news:
        news_lines = "\n".join(f"  - {a.title}" for a in news[:5])
        news_text = f"\nRecent News:\n{news_lines}\n"

    text = f"""{prefix}Anomaly Detected: {breakdown.ticker} {direction}

Contract:         {breakdown.contract}
Strike:           ${breakdown.strike_price:,.2f} {direction} exp {breakdown.expiration_date}
Composite Score:  {breakdown.composite_score:.2f} / 10
Option Price:     ${breakdown.option_price:,.2f}
Volume:           {breakdown.option_volume:,}
Open Interest:    {breakdown.open_interest:,}
Underlying Price: ${breakdown.underlying_price:,.2f}
Underlying Move:  {breakdown.underlying_move_pct:+.2f}%
Already Priced In: {'Yes' if breakdown.already_priced_in else 'No'}
Detected At:      {breakdown.timestamp.strftime('%Y-%m-%d %H:%M:%S')} UTC

Factor Breakdown:
{_factor_rows_text(breakdown)}
{news_text}
---
Generated by Option Finder. This is not financial advice.
"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg.attach(MIMEText(text, "plain"))
    msg.attach(MIMEText(html, "html"))
    return msg
